import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Inbox,Star,CalendarDays,Layers,Archive,BookOpen,Trash2,Search,Plus,Settings,RefreshCw,X,Check,ChevronDown,ChevronRight,ArrowUpRight,Paperclip,Briefcase,Folder,AlertCircle,CheckCircle2,LoaderCircle,Sun,Moon,Menu,Tag as TagIcon} from 'lucide-react';
import {call,connect,subscribe,mutate,attach,attachmentAvailable,demo} from './bridge';
import {Task,Snapshot,ThingsError,fieldAvailable,snapshotData,changedArguments,TaskDraft,draftFromTask,taskWhen,projectIsOpen,quickDefaults,quickEntryArguments,taskBelongsToView} from './types';
import '@openai/mcp-extensions/app/styles.css';
import './style.css';
const views=[{id:'inbox',title:'Inbox',icon:Inbox,color:'blue'},{id:'today',title:'Today',icon:Star,color:'yellow'},{id:'upcoming',title:'Upcoming',icon:CalendarDays,color:'red'},{id:'anytime',title:'Anytime',icon:Layers,color:'teal'},{id:'someday',title:'Someday',icon:Archive,color:'sand'},{id:'logbook',title:'Logbook',icon:BookOpen,color:'green'},{id:'trash',title:'Trash',icon:Trash2,color:'gray'}];
const blank:Snapshot={tasks:[],projects:[],areas:[],tags:[],lists:[],total:0,offset:0,limit:20,nextOffset:null,hasMore:false,capabilities:{}};
type Draft=TaskDraft;
const drafts=new Map<string,Draft>();
const fromTask=draftFromTask;
function dateLabel(value:string|null){if(!value)return '';const date=new Date(`${value}T12:00:00`);return Number.isNaN(+date)?value:date.toLocaleDateString(undefined,{month:'short',day:'numeric'});}
function message(error:unknown){return error instanceof Error?error.message:'The action could not be completed.';}
function IconButton({label,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button type="button" className="icon-button cursor-interaction" aria-label={label} title={label} {...props}>{children}</button>;}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const controls=()=>Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled)')??[]);(ref.current?.querySelector<HTMLElement>('[autofocus]')??controls()[1]??controls()[0])?.focus();const handler=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();close();}if(event.key==='Tab'){const items=controls();if(event.shiftKey&&document.activeElement===items[0]){event.preventDefault();items.at(-1)?.focus();}else if(!event.shiftKey&&document.activeElement===items.at(-1)){event.preventDefault();items[0]?.focus();}}};ref.current?.addEventListener('keydown',handler);return()=>{ref.current?.removeEventListener('keydown',handler);previous?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className="modal" role="dialog" aria-modal="true" aria-label={title} ref={ref}><header><h2>{title}</h2><IconButton label={`Close ${title}`} onClick={close}><X size={18}/></IconButton></header>{children}</section></div>;
}
function Location({snapshot,value,onChange,disabled=false}:{snapshot:Snapshot;value:string;onChange:(value:string)=>void;disabled?:boolean}){const currentProject=snapshot.projects.find(project=>`project:${project.id}`===value&&!projectIsOpen(project));return <select aria-label="Project or area" value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}><option value="">No project or area</option>{currentProject&&<option value={value} disabled>{currentProject.title} · {currentProject.status??'Unavailable'}</option>}{snapshot.areas.map(area=><optgroup label={area.title} key={area.id}><option value={`area:${area.id}`}>{area.title}</option>{snapshot.projects.filter(p=>projectIsOpen(p)&&p.areaId===area.id).map(project=><option key={project.id} value={`project:${project.id}`}>{project.title}</option>)}</optgroup>)}{snapshot.projects.filter(p=>projectIsOpen(p)&&!p.areaId).map(project=><option key={project.id} value={`project:${project.id}`}>{project.title}</option>)}</select>;}
function When({value,onChange,disabled=false,projectTask=false}:{value:string;onChange:(value:string)=>void;disabled?:boolean;projectTask?:boolean}){const selected=!value?'':['anytime','today','tomorrow','someday'].includes(value)?value:'date';const help='Set Anytime or Someday in Things for tasks inside projects.';return <div className="when-control"><select aria-label="When" value={selected} disabled={disabled} title={projectTask?help:undefined} onChange={e=>onChange(e.target.value==='date'?new Date().toLocaleDateString('en-CA'):e.target.value)}><option value="" disabled>Unspecified in Things</option><option value="anytime" disabled={projectTask}>Anytime</option><option value="today">Today</option><option value="tomorrow">Tomorrow</option><option value="someday" disabled={projectTask}>Someday</option><option value="date">Choose a date…</option></select>{selected==='date'&&<input aria-label="Start date" type="date" value={value} disabled={disabled} onChange={e=>onChange(e.target.value||(projectTask?value:'anytime'))}/>} {projectTask&&<small className="muted">{help}</small>}</div>;}
function TaskEditor({task,snapshot,busy,save,close,action,attachTask,reloadTask}:{task:Task;snapshot:Snapshot;busy:boolean;save:(task:Task,args:Record<string,unknown>)=>Promise<void>;close:()=>void;action:(command:string,task:Task)=>Promise<void>;attachTask:(task:Task)=>Promise<void>;reloadTask:(task:Task)=>Promise<Task|undefined>}){
 const [base,setBase]=useState(task);const [draft,setDraft]=useState(()=>drafts.get(task.id)??fromTask(task));const [error,setError]=useState<unknown>();const [conflict,setConflict]=useState<Task>();const [uncertain,setUncertain]=useState(false);const [tagsText,setTagsText]=useState((drafts.get(task.id)?.tags??(task.tags??[]).map(t=>t.title)).join(', '));const [confirmTrash,setConfirmTrash]=useState(false);
 const set=(next:Partial<Draft>)=>setDraft(previous=>{const updated={...previous,...next};drafts.set(task.id,updated);return updated;});
 const args=changedArguments(base,draft);const dirty=Object.keys(args).length>1;
 async function submit(){if(!dirty){close();return;}setError(undefined);try{await save(base,args);drafts.delete(task.id);close();}catch(failure){setError(failure);if(failure instanceof ThingsError){setConflict(failure.response.error?.details?.task);setUncertain(failure.uncertain);}}}
 async function checkLatest(){const latest=await reloadTask(base);if(latest){setBase(latest);setConflict(latest);setError(undefined);setUncertain(false);}}
 return <div className="task-editor"><label className="sr-only" htmlFor={`title-${task.id}`}>Task title</label><input id={`title-${task.id}`} className="editor-title" value={draft.title} onChange={e=>set({title:e.target.value})} maxLength={1000} disabled={busy}/>
 {fieldAvailable(base,'notes')?<textarea aria-label="Task notes" className="editor-notes" placeholder="Notes" value={draft.notes} onChange={e=>set({notes:e.target.value})} rows={3} disabled={busy}/>:<p className="unavailable">Notes are unavailable for this task.</p>}
 {fieldAvailable(base,'tags')&&<div className="editor-tags"><TagIcon size={14}/><label className="sr-only" htmlFor={`tags-${task.id}`}>Tags, separated by commas</label><input id={`tags-${task.id}`} aria-label="Tags, separated by commas" placeholder="Add tags" value={tagsText} onChange={e=>{setTagsText(e.target.value);set({tags:e.target.value.split(',').map(t=>t.trim()).filter(Boolean)});}} list="known-tags" disabled={busy}/><datalist id="known-tags">{snapshot.tags.map(t=><option key={t.id} value={t.title}/>)}</datalist></div>}
 <div className="editor-fields"><label><span><CalendarDays size={14}/> When</span><When value={draft.when} onChange={when=>set({when})} projectTask={draft.location.startsWith('project:')} disabled={busy||!fieldAvailable(base,'when')}/></label><label><span><CalendarDays size={14}/> Deadline</span><div className="deadline-control"><input aria-label="Deadline" type="date" value={draft.deadline} onChange={e=>set({deadline:e.target.value})} disabled={busy||!fieldAvailable(base,'deadline')}/>{draft.deadline&&<IconButton label="Clear deadline" disabled={busy||!fieldAvailable(base,'deadline')} onClick={()=>set({deadline:''})}><X size={13}/></IconButton>}</div></label><label className="location-field"><span><Folder size={14}/> Project or area</span><Location snapshot={snapshot} value={draft.location} onChange={location=>set({location})} disabled={busy||!fieldAvailable(base,'projectId')||!fieldAvailable(base,'areaId')}/></label></div>
 {error!==undefined&&<div className="inline-error" role="alert"><AlertCircle size={15}/><span>{message(error)}{uncertain&&' Your draft is kept. No change will be retried automatically.'}</span></div>}
 {conflict&&<div className="conflict"><strong>Latest in Things</strong><p>{conflict.title}</p>{conflict.notes&&<p>{conflict.notes}</p>}<dl><dt>When</dt><dd>{fieldAvailable(conflict,'when')||fieldAvailable(conflict,'whenKind')||fieldAvailable(conflict,'listIds')?dateLabel(conflict.when)||(taskWhen(conflict)==='today'?'Today':taskWhen(conflict)==='someday'?'Someday':taskWhen(conflict)==='anytime'?'Anytime':'Unspecified in Things'):'Unavailable'}</dd><dt>Deadline</dt><dd>{fieldAvailable(conflict,'deadline')?dateLabel(conflict.deadline)||'None':'Unavailable'}</dd><dt>Tags</dt><dd>{fieldAvailable(conflict,'tags')?(conflict.tags??[]).map(t=>t.title).join(', ')||'None':'Unavailable'}</dd></dl><div className="actions"><button onClick={()=>{setBase(conflict);setDraft(fromTask(conflict));setTagsText((conflict.tags??[]).map(t=>t.title).join(', '));drafts.delete(task.id);setConflict(undefined);setError(undefined);}}>Use latest version</button><button className="primary" disabled={busy} onClick={()=>{setBase(conflict);setConflict(undefined);setError(undefined);}}>Keep my draft for review</button></div><small>Your next Save uses this latest version. Review your fields before saving.</small></div>}
 <div className="editor-footer"><small className="task-id" title={task.id}>ID {task.id}</small><div className="editor-actions"><IconButton label="Attach task to conversation" disabled={busy||!attachmentAvailable()} onClick={()=>attachTask(base)}><Paperclip size={15}/></IconButton><IconButton label="Show in Things" disabled={busy||demo} onClick={()=>action('show',base).catch(setError)}><ArrowUpRight size={15}/></IconButton>{base.status!=='trashed'&&<IconButton label="Move task to Trash" disabled={busy} onClick={()=>setConfirmTrash(true)}><Trash2 size={15}/></IconButton>}<button className="quiet" onClick={close}>Close</button>{uncertain?<button onClick={checkLatest} disabled={busy}>Check latest task</button>:<button className="primary" disabled={busy||!draft.title.trim()||!dirty||!!conflict} onClick={submit}>{busy?<><LoaderCircle size={14} className="spin"/> Saving…</>:'Save'}</button>}</div></div>
 {confirmTrash&&<div className="trash-confirm"><span>Move “{base.title}” to Trash?</span><button onClick={()=>setConfirmTrash(false)}>Keep task</button><button className="danger" disabled={busy} onClick={()=>action('trash',base).then(()=>{drafts.delete(task.id);close();}).catch(setError)}>Move to Trash</button></div>}</div>;
}
function Workspace(){
 const [snapshot,setSnapshot]=useState(blank);const [view,setView]=useState('today');const [selected,setSelected]=useState<string>();const [query,setQuery]=useState('');const [showSearch,setShowSearch]=useState(false);const [connected,setConnected]=useState(false);const [loaded,setLoaded]=useState(false);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [toast,setToast]=useState('');const [modal,setModal]=useState<'quick'|'settings'>();const [navOpen,setNavOpen]=useState(false);const [doctor,setDoctor]=useState<Record<string,any>>();const [theme,setTheme]=useState('system');const [settings,setSettings]=useState<Record<string,any>>({});
 const currentView=useRef(view);const navigation=useRef(0);const request=useRef(0);const snapshotRef=useRef(snapshot);snapshotRef.current=snapshot;const launchHandled=useRef(false);const catalogLoaded=useRef(false);const loadRunning=useRef(false);const pendingLoad=useRef<{seq:number;view:string;append:boolean;offset:number;includeCatalog:boolean;resolve:()=>void}|undefined>(undefined);const searchRef=useRef<HTMLInputElement>(null);const [quick,setQuick]=useState<Draft>({title:'',notes:'',tags:[],when:'anytime',deadline:'',location:''});const [quickError,setQuickError]=useState('');const [quickUncertain,setQuickUncertain]=useState(false);
 useEffect(()=>{currentView.current=view;},[view]);
 function notify(value:string){setToast(value);}
 function openQuick(){setQuick(previous=>previous.title||previous.notes?previous:{...previous,...quickDefaults(currentView.current)});setModal('quick');}
 function load(nextView=currentView.current,append=false,includeCatalog=false){
  const seq=++request.current;setLoading(true);setError('');
  return new Promise<void>(resolve=>{pendingLoad.current?.resolve();const previous=snapshotRef.current;pendingLoad.current={seq,view:nextView,append,includeCatalog:includeCatalog||!catalogLoaded.current,offset:append?previous.nextOffset??previous.offset+previous.tasks.length:0,resolve};void drainLoads();});
 }
 async function drainLoads(){
  if(loadRunning.current)return;loadRunning.current=true;
  while(pendingLoad.current){const job=pendingLoad.current;pendingLoad.current=undefined;
   try{const value=await call('thingsctl_workspace_snapshot',{view:job.view,offset:job.offset,limit:20,...(snapshotRef.current.capabilities.includeCatalog===true?{includeCatalog:job.includeCatalog}:{})});const data=snapshotData(value);if(!data)throw new Error('Things did not return a task list.');if(job.seq!==request.current||job.view!==currentView.current)continue;if(data.view&&data.view!==job.view)throw new Error('Things returned a different task list. Refresh to try again.');if(data.catalogIncluded!==false)catalogLoaded.current=true;setSnapshot(previous=>{const merged=data.catalogIncluded===false?{...data,projects:previous.projects,areas:previous.areas,tags:previous.tags,lists:previous.lists}:data;return job.append?{...merged,view:job.view,offset:previous.offset,tasks:Array.from(new Map([...previous.tasks,...merged.tasks].map(task=>[task.id,task])).values())}:{...merged,view:job.view};});setLoaded(true);
   }catch(failure){if(job.seq===request.current)setError(message(failure));}finally{job.resolve();}
  }
  loadRunning.current=false;setLoading(false);
 }
 useEffect(()=>{const dispose=subscribe(event=>{if(event.type==='connection'){setConnected(event.connected);if(event.message)setError(event.message);}if(event.type==='result'){
   // Host notifications deliver the launcher result. Subsequent UI requests
   // have their own scoped responses and must not be overwritten by it.
   if(launchHandled.current||request.current>0)return;launchHandled.current=true;
   const data=snapshotData(event.value);if(data){catalogLoaded.current=data.catalogIncluded!==false;setSnapshot(data);setLoaded(true);if(data.view){setView(data.view);currentView.current=data.view;}if(event.value.meta?.settings)setSettings(event.value.meta.settings);}else if(event.value.data?.mode==='settings'){setSettings(event.value.data.settings??{});setModal('settings');const startView=event.value.data.settings?.startView??'today';setView(startView);currentView.current=startView;void load(startView);}else if(!event.value.ok)setError(event.value.error?.message??'Unable to load Things.');
  }});connect().then(()=>{if(demo)void load();}).catch(()=>{});return dispose;},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{const typing=(event.target as HTMLElement).matches('input,textarea,select');if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='f'){event.preventDefault();setShowSearch(true);setTimeout(()=>searchRef.current?.focus(),0);}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='n'){event.preventDefault();if(connected&&!busy&&!loading)openQuick();}if(event.key==='Escape'&&!modal){setSelected(undefined);setNavOpen(false);if(!typing){setShowSearch(false);setQuery('');}}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[modal,connected,busy,loading]);
 useEffect(()=>{if(typeof settings.theme==='string'){setTheme(settings.theme);document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.appearanceChoice=settings.theme;}},[settings.theme]);
 useEffect(()=>{const seconds=settings.refreshSeconds??120;if(demo||!connected||seconds<=0)return;const timer=setInterval(()=>{if(!loading&&!busy&&!selected&&!modal&&!document.hidden)void load();},Math.max(15,seconds)*1000);return()=>clearInterval(timer);},[settings.refreshSeconds,connected,loading,busy,selected,modal]);
 function navigate(id:string){if(id===currentView.current){setNavOpen(false);return;}navigation.current++;setView(id);currentView.current=id;setSelected(undefined);setQuery('');setNavOpen(false);setLoaded(false);setSnapshot(previous=>({...previous,view:id,tasks:[],total:null,offset:0,nextOffset:null,hasMore:false}));void load(id);}
 function applyVerifiedTask(task:Task,targetView:string,targetNavigation:number,wasLoaded:boolean,keepInPlace=false){
  if(currentView.current!==targetView||navigation.current!==targetNavigation)return false;
  const membership=keepInPlace?true:taskBelongsToView(task,targetView);if(membership===null&&!wasLoaded)return false;
  setSnapshot(previous=>{const present=previous.tasks.some(item=>item.id===task.id);const keep=membership!==false;const tasks=keep?(present?previous.tasks.map(item=>item.id===task.id?task:item):[...previous.tasks,task]):previous.tasks.filter(item=>item.id!==task.id);return {...previous,tasks,total:previous.total===null?null:previous.total+(keep&&!present?1:!keep&&present?-1:0)};});return true;
 }
 async function action(command:string,task:Task,args:Record<string,unknown>={id:task.id}){const targetView=currentView.current;const targetNavigation=navigation.current;setBusy(true);setError('');try{const value=await mutate(command,args,command==='show'?undefined:task.revision);if(command==='show'){notify('Opened in Things');return;}const stillHere=currentView.current===targetView&&navigation.current===targetNavigation;const verified=value.data?.task as Task|undefined;if(verified){if(stillHere){request.current++;pendingLoad.current?.resolve();pendingLoad.current=undefined;}const cosmetic=command==='update'&&Object.keys(args).every(key=>['id','title','notes','tags'].includes(key));const sameMembership=['status','projectId','areaId','when','whenKind','deadline'].every(key=>(task as any)[key]===(verified as any)[key])&&JSON.stringify([...new Set(task.listIds??[])].sort())===JSON.stringify([...new Set(verified.listIds??[])].sort());const omittedMembership=cosmetic&&sameMembership&&verified.status==='open'&&['inbox','today','upcoming','anytime','someday'].includes(targetView)&&!task.listIds?.includes(targetView);applyVerifiedTask(verified,targetView,targetNavigation,true,omittedMembership);}else if(stillHere)await load(targetView);notify(demo?'Demo change saved':command==='complete'?'Completed in Things':'Saved and verified in Things');if(stillHere&&['complete','reopen','trash'].includes(command))setSelected(undefined);}catch(failure){setError(message(failure));throw failure;}finally{setBusy(false);}}
 async function attachTask(task:Task){try{await attach([task]);notify(demo?'Demo attachment selected':'Task attached to conversation');}catch(failure){setError(message(failure));}}
 async function reloadTask(task:Task){try{const value=await call('thingsctl_get',{id:task.id});const latest=value.data?.task as Task|undefined;if(latest)setSnapshot(previous=>({...previous,tasks:previous.tasks.map(t=>t.id===latest.id?latest:t)}));return latest;}catch(failure){setError(message(failure));}}
 async function addTask(event:React.FormEvent){event.preventDefault();const targetView=currentView.current;const targetNavigation=navigation.current;setBusy(true);setQuickError('');try{const args=quickEntryArguments(quick);const value=await mutate('add',args);setModal(undefined);setQuick({title:'',notes:'',tags:[],when:'anytime',deadline:'',location:''});setQuickUncertain(false);notify(demo?'Demo task added':'Added and verified in Things');const verified=value.data?.task as Task|undefined;if(currentView.current===targetView&&navigation.current===targetNavigation&&(!verified||!applyVerifiedTask(verified,targetView,targetNavigation,false)))await load(targetView);}catch(failure){setQuickError(message(failure));if(failure instanceof ThingsError&&failure.uncertain)setQuickUncertain(true);}finally{setBusy(false);}}
 async function openSettings(){setModal('settings');setDoctor(undefined);try{const value=await call('thingsctl_doctor');setDoctor(value.data);}catch(failure){setDoctor({message:message(failure),connected:false});}if(!demo)try{const value=await call('thingsctl_settings_read');setSettings(value.data?.values??(value as any).values??{});}catch{}}
 async function changeTheme(value:string){setTheme(value);document.documentElement.dataset.theme=value;document.documentElement.dataset.appearanceChoice=value;if(!demo)try{await call('thingsctl_settings_update',{set:{theme:value}});}catch(failure){setError(message(failure));}}
 const config=views.find(v=>v.id===view);const title=config?.title??snapshot.projects.find(p=>`project:${p.id}`===view)?.title??snapshot.areas.find(a=>`area:${a.id}`===view)?.title??'Things';const ViewIcon=config?.icon??Folder;
 const needle=query.toLocaleLowerCase();const tasks=loaded?snapshot.tasks.filter(task=>!needle||[task.title,task.notes??'',...(task.tags??[]).map(t=>t.title)].join('\n').toLocaleLowerCase().includes(needle)):[];
 const completed=view==='logbook';const subtitle=view==='today'?new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}):view==='upcoming'?'What’s on the horizon':view==='inbox'?'A home for everything on your mind':view==='anytime'?'Ready when you are':view==='someday'?'Ideas for another day':view==='logbook'?'A little progress, every day':view==='trash'?'Tasks moved to Trash':'One step at a time';
 return <div className={`workspace ${navOpen?'nav-open':''}`} data-demo={demo?'true':'false'}>
 <aside className="sidebar" aria-label="Task lists"><div className="sidebar-brand"><span className="app-mark"><Check size={18}/></span><span>ThingsCTL</span><IconButton label="Close navigation" onClick={()=>setNavOpen(false)}><X size={16}/></IconButton></div><nav>{views.map(({id,title,icon:Icon,color},index)=><React.Fragment key={id}>{index===5&&<div className="nav-separator"/>}<button className={`nav-button cursor-interaction ${color}`} aria-current={view===id?'page':undefined} onClick={()=>navigate(id)}><Icon size={18} fill={id==='today'?'currentColor':'none'}/><span>{title}</span>{view===id&&loaded&&snapshot.total!==null&&<small>{snapshot.total}</small>}</button></React.Fragment>)}</nav><div className="areas">{snapshot.areas.map(area=><section key={area.id}><button className="area-heading" aria-current={view===`area:${area.id}`?'page':undefined} onClick={()=>navigate(`area:${area.id}`)}><Briefcase size={15}/><span>{area.title}</span></button>{snapshot.projects.filter(p=>projectIsOpen(p)&&p.areaId===area.id).map(project=><button className="nav-button project-button" key={project.id} aria-current={view===`project:${project.id}`?'page':undefined} onClick={()=>navigate(`project:${project.id}`)}><span className="project-ring"/><span>{project.title}</span></button>)}</section>)}{snapshot.projects.filter(p=>projectIsOpen(p)&&!p.areaId).map(project=><button className="nav-button project-button" key={project.id} aria-current={view===`project:${project.id}`?'page':undefined} onClick={()=>navigate(`project:${project.id}`)}><span className="project-ring"/><span>{project.title}</span></button>)}</div><footer className="sidebar-footer"><button onClick={openSettings}><Settings size={16}/><span>Settings</span></button>{demo&&<small>Demo data</small>}</footer></aside>
 {navOpen&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setNavOpen(false)}/>}
 <main className="main"><div className="toolbar"><div className="toolbar-left"><IconButton label="Open navigation" className="icon-button mobile-nav" onClick={()=>setNavOpen(true)}><Menu size={19}/></IconButton><span className="toolbar-brand">ThingsCTL</span>{demo&&<span className="demo-badge">Demo data</span>}</div><div className="toolbar-actions"><IconButton label="Search loaded tasks" onClick={()=>{setShowSearch(!showSearch);setTimeout(()=>searchRef.current?.focus(),0);}}><Search size={17}/></IconButton><IconButton label="Refresh task list" disabled={loading||busy||!connected} onClick={()=>load(currentView.current,false,true)}><RefreshCw size={16} className={loading?'spin':''}/></IconButton><IconButton label="New task" disabled={!connected||busy||loading} onClick={openQuick}><Plus size={20}/></IconButton></div></div>
 <div className="content"><header className="list-heading"><div className={`heading-symbol ${config?.color??'blue'}`}><ViewIcon size={34} fill={view==='today'?'currentColor':'none'}/></div><div><h1>{title}</h1><p>{subtitle}</p></div></header>
 {showSearch&&<div className="search-bar"><Search size={16}/><input ref={searchRef} type="search" aria-label="Search loaded tasks" placeholder="Search these tasks" value={query} onChange={e=>setQuery(e.target.value)}/><IconButton label="Close search" onClick={()=>{setShowSearch(false);setQuery('');}}><X size={15}/></IconButton></div>}
 {query&&<p className="search-caption">{tasks.length} match{tasks.length===1?'':'es'} in {snapshot.tasks.length} loaded tasks{snapshot.hasMore?' · More tasks are available':''}</p>}
 {error&&<div className="error-banner" role="alert"><AlertCircle size={17}/><span>{error}</span>{!loaded&&<button className="quiet" disabled={loading||busy||!connected} onClick={()=>load(currentView.current,false,true)}>Retry</button>}<IconButton label="Dismiss error" onClick={()=>setError('')}><X size={15}/></IconButton></div>}
 {!loaded&&!error&&<div className="empty-state"><LoaderCircle size={25} className="spin"/><h2>{loading?`Loading ${title}`:'Connecting to Things'}</h2><p>{loading?'Your tasks will appear here.':'Open a Things list to begin.'}</p></div>}
 {loaded&&tasks.length===0&&<div className="empty-state"><ViewIcon size={29} className={config?.color}/><h2>{query?'No matching tasks':view==='logbook'?'A fresh start':'All clear'}</h2><p>{query?'Try another word or load more tasks.':view==='trash'?'There are no tasks in Trash.':view==='logbook'?'Completed tasks will appear here.':'A little room to focus.'}</p>{!query&&!['logbook','trash'].includes(view)&&<button className="quiet" onClick={openQuick}><Plus size={14}/> Add a task</button>}</div>}
 <div className="task-list" role="list" aria-label={`${title} tasks`}>{tasks.map((task,index)=>{const dateGroup=view==='upcoming'&&(index===0||task.when!==tasks[index-1].when);const project=snapshot.projects.find(p=>p.id===task.projectId);return <React.Fragment key={task.id}>{dateGroup&&<div className="date-section">{dateLabel(task.when)||'Date unavailable'}</div>}<div role="listitem" className={`task ${selected===task.id?'expanded':''} ${task.status!=='open'?'finished':''}`}><div className="task-row" tabIndex={0} onKeyDown={event=>{if(event.target!==event.currentTarget)return;if(event.key==='Enter'){event.preventDefault();setSelected(selected===task.id?undefined:task.id);}if(event.key===' '&&view!=='trash'&&!busy&&!loading){event.preventDefault();void action(task.status==='open'?'complete':'reopen',task).catch(()=>{});}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const rows=Array.from(document.querySelectorAll<HTMLElement>('.task-row'));rows[index+(event.key==='ArrowDown'?1:-1)]?.focus();}}}><button className="task-checkbox cursor-interaction" role="checkbox" aria-checked={task.status==='completed'||task.status==='canceled'} aria-label={`${task.status==='open'?'Complete':'Reopen'} ${task.title}`} disabled={busy||loading||view==='trash'} onClick={()=>action(task.status==='open'?'complete':'reopen',task).catch(()=>{})}>{task.status!=='open'&&task.status!=='trashed'&&<Check size={13}/>}</button><button className="task-title-button" aria-expanded={selected===task.id} onClick={()=>setSelected(selected===task.id?undefined:task.id)}><span className="task-title">{task.title}</span>{project&&!view.startsWith('project:')&&<small className="project-label">{project.title}</small>}</button><div className="task-metadata">{!!task.tags?.length&&<span className="tag-pill">{task.tags[0].title}</span>}{task.deadline&&<span className="deadline-label" title={`Deadline ${task.deadline}`}><CalendarDays size={12}/>{dateLabel(task.deadline)}</span>}</div>{task.notes&&<span className="notes-dot" aria-label="Has notes"/>}</div>{selected===task.id&&<TaskEditor key={task.id} task={task} snapshot={snapshot} busy={busy||loading} save={(base,args)=>action('update',base,args)} close={()=>setSelected(previous=>previous===task.id?undefined:previous)} action={(command,task)=>action(command,task)} attachTask={attachTask} reloadTask={reloadTask}/>}</div></React.Fragment>;})}</div>
 {loaded&&snapshot.hasMore&&<button className="load-more" disabled={loading||busy||snapshot.nextOffset===null} onClick={()=>load(view,true)}>{loading?'Loading…':'Load more'}</button>}
 {loaded&&!['logbook','trash'].includes(view)&&tasks.length>0&&!selected&&!query&&<button className="add-row" disabled={busy||loading} onClick={openQuick}><Plus size={16}/><span>New To-Do</span><kbd>⌘ N</kbd></button>}
 </div><footer className="main-footer"><span><i className={connected&&loaded?'connected-dot':'disconnected-dot'}/>{demo?'Fictional sample workspace':connected&&loaded?'Things 3':connected?'Waiting for Things':'Disconnected'}{busy?' · Saving…':loading?' · Refreshing…':''}</span><button onClick={openSettings}>Connection & settings</button></footer></main>
 {toast&&<div role="status" className="toast"><CheckCircle2 size={17}/>{toast}</div>}
 {modal==='quick'&&<Modal title="New To-Do" close={()=>setModal(undefined)}><form className="quick-form" onSubmit={addTask}><label className="sr-only" htmlFor="quick-title">New task title</label><input id="quick-title" autoFocus className="quick-title" placeholder="What’s on your mind?" value={quick.title} onChange={e=>setQuick({...quick,title:e.target.value})} maxLength={1000} required disabled={busy}/><textarea aria-label="New task notes" placeholder="Notes" value={quick.notes} onChange={e=>setQuick({...quick,notes:e.target.value})} rows={3} disabled={busy}/><div className="editor-fields"><label><span>When</span><When value={quick.when} onChange={when=>setQuick({...quick,when})} projectTask={quick.location.startsWith('project:')} disabled={busy}/></label><label><span>Deadline</span><input aria-label="New task deadline" type="date" value={quick.deadline} onChange={e=>setQuick({...quick,deadline:e.target.value})} disabled={busy}/></label><label className="location-field"><span>Project or area</span><Location snapshot={snapshot} value={quick.location} onChange={location=>setQuick({...quick,location,when:location.startsWith('project:')&&['anytime','someday'].includes(quick.when)?'':quick.when})} disabled={busy}/></label></div>{quickError&&<div className="inline-error" role="alert"><AlertCircle size={15}/><span>{quickError}{quickUncertain&&' Your draft is kept. Check Things before retrying this operation.'}</span></div>}<footer><span>{demo?'Adds a fictional demo task':!quick.location&&quick.when==='anytime'?'Adds to Inbox':'Adds directly to Things'}</span><button type="submit" className="primary" disabled={busy||!quick.title.trim()||quickUncertain}>{busy?'Adding…':'Add To-Do'}</button></footer></form></Modal>}
 {modal==='settings'&&<Modal title="ThingsCTL Settings" close={()=>setModal(undefined)}><div className="settings-content"><section><h3>Connection</h3><p>{demo?'Demo data · Things is not accessed':doctor?(doctor.connected===false?'Connection needs attention':'Things 3'):'Checking connection…'}</p>{doctor?.message&&<p className="muted">{doctor.message}</p>}<button onClick={()=>call('thingsctl_doctor').then(value=>setDoctor(value.data)).catch(failure=>setDoctor({message:message(failure),connected:false}))}><RefreshCw size={14}/> Check connection</button></section><section><h3>Appearance</h3><label className="settings-row"><span>Theme</span><select aria-label="Theme" value={theme} onChange={e=>changeTheme(e.target.value)}><option value="system">Follow system</option><option value="light">Light</option><option value="dark">Dark</option></select></label></section><section><h3>Available in this version</h3><p className="muted">Tasks, notes, tags, projects, areas, start dates, and deadlines use the Things automation interface.</p><p className="muted">Checklists, headings, Evening, reminders, and repeating rules are unavailable until their supported integration can be verified.</p></section><section><h3>Keyboard</h3><dl className="shortcuts"><dt>New To-Do</dt><dd>⌘ N</dd><dt>Search this list</dt><dd>⌘ F</dd><dt>Open focused task</dt><dd>Enter</dd><dt>Complete focused task</dt><dd>Space</dd><dt>Move between tasks</dt><dd>↑ ↓</dd><dt>Close editor</dt><dd>Escape</dd></dl></section><small>ThingsCTL is an independent integration. Things is a trademark of Cultured Code.</small></div></Modal>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<Workspace/>);
